site_name: Træfik
site_description: Træfik Documentation
site_author: containo.us
site_url: https://docs.traefik.io
dev_addr: 0.0.0.0:8000

repo_name: 'GitHub'
repo_url: 'https://github.com/containous/traefik'

docs_dir: 'docs'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  language: en
  include_sidebar: true
  favicon: img/traefik.icon.png
  logo: img/traefik.logo.png
  palette:
    primary: 'blue'
    accent: 'light blue'
  feature:
    tabs: false
  palette:
    primary: 'cyan'
    accent: 'cyan'
  i18n:
    prev: 'Previous'
    next: 'Next'

copyright: "Copyright &copy; 2016-2018 Containous SAS"

google_analytics:
  - 'UA-51880359-3'
  - 'docs.traefik.io'

# Options
# Comment because the call of the CDN is very slow.
#extra:
#  social:
#    - type: 'github'
#      link: 'https://github.com/containous/traefik'
#    - type: 'stack-overflow'
#      link: 'https://stackoverflow.com/questions/tagged/traefik'
#    - type: 'slack'
#      link: 'https://traefik.herokuapp.com'
#    - type: 'twitter'
#      link: 'https://twitter.com/traefikproxy'

extra_css:
  - theme/styles/extra.css
  - theme/styles/atom-one-light.css

extra_javascript:
  - theme/js/hljs/highlight.pack.js
  - theme/js/extra.js

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - markdown_include.include:
      base_path: /mkdocs/docs/includes/
      encoding: utf-8
  - toc:
      permalink: true

# Page tree
pages:
  - 'Getting Started':
    - 'What is Traefik?': 'index.md'
    - 'Concepts': 'getting-started/concepts.md'
    - 'Quick Start': 'getting-started/quick-start.md'
    - 'Configuration Overview': 'getting-started/configuration-overview.md'
    - 'Download': 'getting-started/download.md'
  - 'Configuration':
    - 'The Dashboard': 'configuration/dashboard.md'
    - 'Routing & Load Balancing':
      - 'Entrypoints':
        - 'Overview': 'configuration/routing-load-balancing/entrypoints/overview.md'
        - 'Capturing HTTP traffic': 'configuration/routing-load-balancing/entrypoints/http.md'
        - 'Configuring HTTPS': 'configuration/routing-load-balancing/entrypoints/https.md'
      - 'Frontends':
        - 'Overview': 'configuration/routing-load-balancing/frontends/overview.md'
        - 'Matchers':
          - 'Overview': 'configuration/routing-load-balancing/frontends/matchers/overview.md'
        - 'Modifiers':
          - 'Overview': 'configuration/routing-load-balancing/frontends/modifiers/overview.md'
      - 'Backends':
        - 'Overview':  'configuration/routing-load-balancing/backends/overview.md'
    - 'Providers':
      - 'Overview': 'configuration/providers/overview.md'
      - 'Kubernetes': 'configuration/providers/kubernetes.md'
      - 'Docker': 'configuration/providers/docker.md'
      - 'Swarm': 'configuration/providers/swarm.md'
      - 'Mesos': 'configuration/providers/mesos.md'
      - 'Marathon': 'configuration/providers/marathon.md'
      - 'Eureka': 'configuration/providers/eureka.md'
      - 'Service Fabric': 'configuration/providers/service-fabric.md'
      - 'BoltDB': 'configuration/providers/boltdb.md'
      - 'Consul': 'configuration/providers/consul.md'
      - 'BoltDB': 'configuration/providers/boltdb.md'
      - 'Consul': 'configuration/providers/consul.md'
      - 'Consul Catalog': 'configuration/providers/consul-catalog.md'
      - 'DynamoDB': 'configuration/providers/dynamodb.md'
      - 'ECS': 'configuration/providers/ecs.md'
      - 'Etcd': 'configuration/providers/etcd.md'
      - 'Eureka': 'configuration/providers/eureka.md'
      - 'Rancher': 'configuration/providers/rancher.md'
      - 'Rest': 'configuration/providers/rest.md'
      - 'Zookeeper': 'configuration/providers/zookeeper.md'
    - 'Metrics': 'configuration/metrics.md'
    - 'Logs': 'configuration/logs.md'
    - 'Tracing': 'configuration/tracing.md'
    - 'Custom Error Pages': 'configuration/custom-error-pages.md'
  - 'Advanced Configuation':
    - 'API': 'advanced/api.md'
    - 'Debug Mode': 'advanced/debug-mode.md'
    - 'Health Check': 'advanced/health.md'
  - 'Use Cases':
    - 'Configuration Examples': 'use-cases/examples.md'
    - 'Swarm Mode Cluster': 'use-cases/swarm-mode.md'
    - 'Swarm Cluster': 'use-cases/swarm-cluster.md'
    - 'Let''s Encrypt & Docker': 'use-cases/let-s-encrypt.md'
    - 'Kubernetes': 'use-cases/kubernetes.md'
    - 'Marathon': 'use-cases/marathon.md'
    - 'Key-value Store Configuration': 'use-cases/key-value.md'
    - 'Clustering/HA': 'use-cases/clustering.md'
    - 'gRPC Example': 'use-cases/grpc.md'
    - 'Traefik cluster example with Swarm': 'use-cases/cluster-with-swarm.md'
  - 'Contributing':
    - 'Contributing': 'contributing/contributing.md'
    - 'Collecting Data': 'contributing/collecting-data.md'
  - 'Resources': 'resources.md'

